### ISSUE TITLE
Finalise the documentation

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/radi-project-wundertoolswrapper#5]
Add minimum requirements to the documentation.

**Comment by james-nesbitt** [comment]
this documentation state now needs review ( @iler )  Please check the wiki and the README

**Comment by james-nesbitt** [comment]
hmmm, just adding a contributors page.

**Comment by james-nesbitt** [comment]
after #24 was merged, documentation seems pretty good.  Can we close this issue?

**Comment by iler** [comment]
I think this is ok but would like that @tharna would have a look at this too.

**Comment by tharna** [comment]
Although there is the link to the wiki pages I think it would be nice to mention how to get your environment up and how to access it after radifying the project.
Just a couple more lines at the end ;)

**Comment by james-nesbitt** [comment]
@tharna this should help : https://github.com/wunderkraut/radi-project-wundertoolswrapper/pull/31

**Comment by tharna** [comment]
Seems good to me.
